import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Input } from "@chakra-ui/react"
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [minerId, setMinerId] = useState<string>('')

  const handleChange = async (e: any) => {
    setMinerId(e.target.value);
  }

  const handleSubmit = async (e: any) => {
    console.log(minerId)
    const response = await fetch("http://localhost:8080/mintCredential", { method: "POST", headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ minerId: minerId }) })
    const reputationScore = await response.json()
    alert(`Minting Credential with repuation score of ${reputationScore}`)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Input placeholder='minerId' onChange={handleChange} value={minerId} />
        <Button onClick={handleSubmit}>Submit</Button>
      </main>
    </>
  )
}
